from assignments.evidencia_2.constantes import LIMITE_SUPERIOR

MENU_PRINCIPAL = 'PROPUESTA ELEGIDA:\nANÁLISIS DE RENDIMIENTO DE APLICACIONES EN FUNCIÓN DEL SISTEMA OPERATIVO: THREADS VS PROCESOS\n\nObjetivos de esta Fase:\nUsar python y experimentar con una aplicacion al ejecutar tareas concurrentes mediante hilos y procesos.\n\n¿Qué se espera comprobar y realizar?\n\nCarga CPU-Bound: Forzar un estrés real y controlado en el procesador mediante un algoritmo exhaustivo de cálculo de números primos\n(Rango: 1 a 150.000), habiendo removido deliberadamente optimizaciones matemáticas con fines estrictamente didácticos.\n\nAislamiento de Recursos: Demostrar empíricamente cómo el Planificador del Sistema Operativo asigna esta tarea a un único hilo, o a varios\nsaturando un solo núcleo lógico al 100% de su capacidad mientras el resto de la arquitectura permanece en reposo o varios núcleos.\n\nTelemetría de Base: Registrar el tiempo exacto de procesamiento para utilizarlo como métrica de control\ncomparativa entre diferentes implementaciones, monohilo, concurrentes y paralelas.\n\n\nA continuación, elija una opción:\n\n1 - Ejecutar prueba secuencial\n\n2 - Ejecutar prueba multihilo\n\n3 - Ejecutar prueba multiproceso\n\n4 - Ver informe\n\n0 - Volver\n\n\n\nIngrese N° de opción: '

ERROR_MENU = '¡ERROR!\n\nPor favor, ingrese un NÚMERO válido. Presione ENTER para continuar '

CALCULANDO_PRIMOS = f'Calculando números primos desde el 1 hasta el {LIMITE_SUPERIOR}...\n\n\nPROCESAMIENTO EN CURSO, AGUARDE POR FAVOR...\n\n\nEl proceso activo se encuentra en estado de Ejecución (Running) bajo Modo Usuario.\n\nGuía de Verificación en Tiempo Real:\n\n1. Abra el Administrador de Tareas (Windows) o ejecute "htop" (Linux).\n\n2. En la pestaña de Procesos, localice la instancia activa de "python.exe" correspondiente a este script.\n\n3. Diríjase a la pestaña de Rendimiento -> CPU.\n\n4. Haga clic derecho sobre el gráfico de CPU y seleccione: "Cambiar gráfico a -> Procesadores lógicos"\n\n5. Observe cómo la carga de trabajo CPU-Bound es ejecutada por un único hilo principal de manera secuencial.\n\n6. Dependiendo del Scheduler del sistema operativo, el hilo puede migrar dinámicamente entre distintos núcleos lógicos,\npor lo que la actividad puede distribuirse visualmente entre varios procesadores.\n\n7. Aun así, el consumo total permanecerá limitado aproximadamente a la capacidad de ejecución de un único thread lógico,\nlo que evidencia la naturaleza secuencial y monohilo de esta implementación.\n\n'

ESPERANDO_RESULTADOS = 'Esperando resultados... Esto puede tardar varios segundos dependiendo de la capacidad de su CPU... Aguarde por favor...\n\n'

def get_mensaje_exito(primos_encontrados, tiempo_total):
    return f'¡Cálculo finalizado con éxito!\nCantidad de números primos encontrados: {len(primos_encontrados)}\nTiempo total de ejecución: {tiempo_total:.4f} segundos\nPresione ENTER para continuar'